# Generated by Django 3.0.8 on 2021-05-17 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alrm', models.CharField(choices=[('OK', 'Последняя попытка сохранения прошла успешно'), ('Bag', 'Ошибка сохранения, проверьте правильность вносимых данных')], max_length=128, verbose_name='message')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Вертикальный', 'Вертикальный'), ('Горизонтальный', 'Горизонтальный')], max_length=128, verbose_name='Вид емкости')),
                ('pub_date', models.DateField(default=datetime.date.today, verbose_name='дата создания')),
                ('name', models.CharField(choices=[('Резервуар Д', 'Резервуар Д'), ('Резервуар 5', 'Резервуар 5'), ('Резервуар 6', 'Резервуар 6'), ('Резервуар 7', 'Резервуар 7'), ('Резервуар 8', 'Резервуар 8'), ('Резервуар 65', 'Резервуар 65'), ('Резервуар 66', 'Резервуар 66'), ('Резервуар 67', 'Резервуар 67')], max_length=128, verbose_name='номер емкости')),
                ('height', models.IntegerField(default=0, verbose_name='высота взлива')),
                ('temperature_1', models.FloatField(default=0, verbose_name='температура низ')),
                ('temperature_2', models.FloatField(default=0, verbose_name='температура середина')),
                ('temperature_3', models.FloatField(default=0, verbose_name='температура верх')),
                ('density_1', models.FloatField(default=0, verbose_name='плотность низ')),
                ('density_2', models.FloatField(default=0, verbose_name='плотность середина')),
                ('density_3', models.FloatField(default=0, verbose_name='плотность верх')),
                ('water', models.IntegerField(default=0, verbose_name='подтоварная вода')),
                ('calculations', models.FloatField(default=0, verbose_name='расчетный объем')),
            ],
        ),
        migrations.CreateModel(
            name='Sort_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_data', models.DateField(default=datetime.date.today, verbose_name='дата отбора')),
            ],
        ),
    ]
