# Generated by Django 3.2.13 on 2022-07-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_package_write_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sort_data',
        ),
    ]
